INSERT INTO excercises (id, name, description, equipment_needed, excercise_type, intensity_level)
VALUES
  (1, 'Hamstring Stretch', 'Stretching the muscles at the back of the thigh', 'None', 'stretch', 'Low'),
  (2, 'Quadriceps Stretch', 'Stretching the muscles at the front of the thigh', 'None', 'stretch', 'Low'),
  (3, 'Calf Stretch', 'Stretching the muscles in the lower leg', 'None', 'stretch', 'Low'),
  (4, 'Butterfly Stretch', 'Stretching the inner thighs and groin area', 'None', 'stretch', 'Low'),
  (5, 'Shoulder Stretch', 'Stretching the muscles in the shoulders', 'None', 'stretch', 'Low'),
  (6, 'Chest Stretch', 'Stretching the muscles in the chest', 'None', 'stretch', 'Low'),
  (7, 'Tricep Stretch', 'Stretching the muscles in the back of the upper arm', 'None', 'stretch', 'Low'),
  (8, 'Hip Flexor Stretch', 'Stretching the muscles in the front of the hip', 'None', 'stretch', 'Low'),
  (9, 'Standing Forward Bend', 'Stretching the hamstrings and lower back', 'None', 'stretch', 'Low'),
  (10, 'Spinal Twist', 'Stretching the muscles along the spine', 'None', 'stretch', 'Low'),
  (11, 'Neck Stretch', 'Stretching the muscles in the neck', 'None', 'stretch', 'Low'),
  (12, 'Wrist Stretch', 'Stretching the muscles in the wrists and forearms', 'None', 'stretch', 'Low'),
  (13, 'Ankle Circles', 'Stretching and mobilizing the ankles', 'None', 'stretch', 'Low'),
  (14, 'Side Bend Stretch', 'Stretching the muscles along the sides of the body', 'None', 'stretch', 'Low'),
  (15, 'Groin Stretch', 'Stretching the muscles in the inner thighs', 'None', 'stretch', 'Low'),
  (16, 'Adductor Stretch', 'Stretching the muscles in the groin and inner thighs', 'None', 'stretch', 'Low'),
  (17, 'IT Band Stretch', 'Stretching the iliotibial (IT) band', 'None', 'stretch', 'Low'),
  (18, 'Upper Back Stretch', 'Stretching the muscles in the upper back', 'None', 'stretch', 'Low'),
  (19, 'Standing Quad Stretch', 'Stretching the quadriceps muscles', 'None', 'stretch', 'Low'),
  (20, 'Pigeon Pose', 'Stretching the hip flexors and glutes', 'None', 'stretch', 'Low');
  (21, 'Standard Push-ups', 'Basic form of push-ups', 'None', 'bodyweight', 'Medium'),
  (22, 'Incline Push-ups', 'Hands elevated on a bench or step', 'Bench or step', 'bodyweight', 'Low'),
  (23, 'Decline Push-ups', 'Feet elevated on a bench or step', 'Bench or step', 'bodyweight', 'Medium'),
  (24, 'Close Grip Push-ups', 'Hands positioned closer together', 'None', 'bodyweight', 'Medium'),
  (25, 'Wide Grip Push-ups', 'Hands placed wider than shoulder-width apart', 'None', 'bodyweight', 'Medium'),
  (26, 'Plyometric Push-ups', 'Explosive push-ups with a lift-off', 'None', 'bodyweight', 'High'),
  (27, 'One-Arm Push-ups', 'Push-ups performed with one arm', 'None', 'bodyweight', 'High'),
  (28, 'Clapping Push-ups', 'Explosive push-ups with a mid-air clap', 'None', 'bodyweight', 'High'),
  (29, 'Standard Sit-ups', 'Basic form of sit-ups', 'None', 'bodyweight', 'Low'),
  (30, 'Crunches', 'Partial sit-ups with a focus on abdominal contraction', 'None', 'Medium'),
  (31, 'Reverse Crunches', 'Lifting the hips off the ground while keeping the upper back on the ground', 'None', 'bodyweight', 'Medium'),
  (32, 'Bicycle Crunches', 'Alternating knee-to-elbow motion while performing crunches', 'None', 'bodyweight', 'High'),
  (33, 'Russian Twists', 'Twisting the torso from side to side while sitting on the ground', 'None', 'bodyweight', 'Medium'),
  (34, 'Leg Raises', 'Lifting the legs off the ground while lying down', 'None', 'bodyweight', 'High'),
  (35, 'V-ups', 'Simultaneously lifting the legs and upper body to form a V shape', 'None', 'bodyweight', 'High'),
  (36, 'Plank Jacks', 'Combining plank position with a jumping jack motion', 'None', 'bodyweight', 'High');
  (37, 'Forward Lunges', 'Stepping forward and bending the knees to lower the body', 'None', 'bodyweight', 'Medium'),
  (38, 'Reverse Lunges', 'Stepping backward and bending the knees to lower the body', 'None', 'bodyweight', 'Medium'),
  (39, 'Walking Lunges', 'Performing alternating lunges while moving forward', 'None', 'bodyweight', 'Medium'),
  (40, 'Side Lunges', 'Stepping to the side and bending the knee of the leading leg', 'None', 'bodyweight', 'Medium'),
  (41, 'Curtsy Lunges', 'Crossing one leg behind the other and bending the knees', 'None', 'bodyweight', 'Medium'),
  (42, 'Jumping Lunges', 'Performing lunges with a jump and switching legs in mid-air', 'None', 'bodyweight', 'High'),
  (43, 'Plyometric Lunges', 'Explosive lunges with a jump and quick switch of legs', 'None', 'bodyweight', 'High'),
  (44, 'Split Squat', 'Performing a lunge with one foot elevated behind on a bench or step', 'Bench or step', 'bodyweight', 'Medium');
  (45, 'Standard Mountain Climbers', 'Starting in a high plank position and alternating bringing knees toward the chest', 'None', 'bodyweight', 'Medium'),
  (46, 'Cross-Body Mountain Climbers', 'Performing mountain climbers with knee-to-opposite-elbow movement', 'None', 'bodyweight', 'Medium'),
  (47, 'Spiderman Mountain Climbers', 'Bringing knees to the side and outside of the same elbow in a crawling motion', 'None', 'bodyweight', 'Medium'),
  (48, 'Mountain Climber Sliders', 'Performing mountain climbers with sliders or towels under the feet for added challenge', 'Sliders or towels', 'bodyweight', 'High'),
  (49, 'Single-Leg Mountain Climbers', 'Performing mountain climbers with one leg extended while the other knee is brought toward the chest', 'None', 'bodyweight', 'High'),
  (50, 'Mountain Climber Burpees', 'Combining mountain climbers with a burpee exercise', 'None', 'bodyweight', 'High'),
  (51, 'Wide Mountain Climbers', 'Performing mountain climbers with a wider stance for increased hip mobility', 'None', 'bodyweight', 'Medium'),
  (52, 'Mountain Climber Taps', 'Bringing each foot out to the side to tap the ground while in a plank position', 'None', 'bodyweight', 'Medium'),
  (53, 'Standard Burpee', 'Starting in a standing position, dropping to a plank, performing a push-up, jumping back to the feet, and finishing with a jump', 'None', 'bodyweight', 'High'),
  (54, 'Burpee with Push-up', 'Adding a push-up in the plank position before jumping back to the feet', 'None', 'bodyweight', 'High'),
  (55, 'Burpee Box Jump', 'After the jump back to the feet, jumping onto a box or elevated surface', 'Box or elevated surface', 'bodyweight', 'High'),
  (56, 'Burpee Tuck Jump', 'Adding a tuck jump at the end of the burpee, bringing knees toward the chest', 'None', 'bodyweight', 'High'),
  (57, 'Burpee Pull-up', 'Performing a pull-up or chin-up after the jump back to the feet', 'Pull-up bar or equipment', 'bodyweight', 'High'),
  (58, 'Burpee Broad Jump', 'Replacing the vertical jump with a long horizontal jump after the jump back to the feet', 'None', 'bodyweight', 'High'),
  (59, 'Burpee Knee Tuck', 'Performing a knee tuck while in the plank position before jumping back to the feet', 'None', 'bodyweight', 'High'),
  (60, 'Burpee Plank Jack', 'Performing a plank jack by jumping the feet wide and back together while in the plank position', 'None', 'bodyweight', 'High'),
  (61, 'Standard Jumping Jacks', 'Basic form of jumping jacks with arms and legs extended out', 'None', 'bodyweight', 'Low'),
  (62, 'Cross Jacks', 'Crossing arms and legs during the jumping motion', 'None', 'bodyweight', 'Medium'),
  (63, 'Star Jacks', 'Jumping out into a star shape with arms and legs extended wide', 'None', 'bodyweight', 'Medium'),
  (64, 'Power Jacks', 'Adding a squat before jumping into the jumping jack motion', 'None', 'bodyweight', 'High'),
  (65, 'Seal Jacks', 'Clapping hands behind the back during the jumping motion', 'None', 'bodyweight', 'Medium'),
  (66, 'Plyo Jacks', 'Performing explosive and quick jumping jacks with a higher jump', 'None', 'bodyweight', 'High'),
  (67, 'Wide-to-Narrow Jacks', 'Starting with wide-arm jumping jacks and then transitioning to narrow-arm jumping jacks', 'None', 'bodyweight', 'Medium'),
  (68, 'Double Jacks', 'Performing two jumping jacks consecutively before landing', 'None', 'bodyweight', 'Medium'),
  (69, 'Standard Wall Sit', 'Sitting against a wall with thighs parallel to the ground', 'None', 'bodyweight', 'Medium'),
  (70, 'One-Legged Wall Sit', 'Performing a wall sit on one leg while the other leg is raised', 'None', 'bodyweight', 'High'),
  (71, 'Weighted Wall Sit', 'Holding weights or a weight plate during a wall sit', 'Weights or weight plate', 'bodyweight', 'High'),
  (72, 'Banded Wall Sit', 'Performing a wall sit with a resistance band around the thighs', 'Resistance band', 'bodyweight', 'Medium'),
  (73, 'Pulse Wall Sit', 'Adding small pulsing movements while holding the wall sit position', 'None', 'bodyweight', 'High'),
  (74, 'Wall Sit with Leg Lifts', 'Lifting one leg off the ground while maintaining the wall sit position', 'None', 'bodyweight', 'High'),
  (75, 'Wall Sit with Overhead Press', 'Holding weights and performing overhead presses during a wall sit', 'Weights', 'bodyweight', 'High'),
  (76, 'Wall Sit with Lateral Raises', 'Holding weights and performing lateral raises during a wall sit', 'Weights', 'bodyweight', 'High'),
  (77, 'Standard Plank', 'Holding a straight-arm plank position', 'None', 'bodyweight', 'Medium'),
  (78, 'Forearm Plank', 'Holding a plank position on forearms', 'None', 'bodyweight', 'Medium'),
  (79, 'Side Plank', 'Holding a plank position on one side with arm extended upwards', 'None', 'bodyweight', 'Medium'),
  (80, 'Extended Plank', 'Holding a plank position with arms extended forward', 'None', 'bodyweight', 'Medium'),
  (81, 'Plank with Shoulder Taps', 'Performing alternating shoulder taps while in a plank position', 'None', 'bodyweight', 'High'),
  (82, 'Plank Jacks', 'Jumping legs wide and back together while in a plank position', 'None', 'bodyweight', 'High'),
  (83, 'Spiderman Plank', 'Bringing knee to elbow in a plank position alternating sides', 'None', 'bodyweight', 'High'),
  (84, 'Plank with Knee Tucks', 'Bringing knees towards chest while in a plank position', 'None', 'bodyweight', 'High'),
  (85, 'Hanging Leg Raises', 'Lifting legs while hanging from a bar', 'Pull-up bar', 'bodyweight', 'Medium'),
  (86, 'Bench Leg Raises', 'Lying on a bench and raising legs towards chest', 'Bench', 'bodyweight', 'Medium'),
  (87, 'Seated Leg Raises', 'Sitting on a chair or bench and lifting legs', 'Chair or bench', 'bodyweight', 'Low'),
  (88, 'V-Ups', 'Lying on the ground and lifting legs and upper body into a V shape', 'None', 'bodyweight', 'High'),
  (89, 'Lying Leg Raises', 'Lying on the ground and lifting legs towards the ceiling', 'None', 'bodyweight', 'Medium'),
  (90, 'Side Leg Raises', 'Lying on the side and lifting top leg towards the ceiling', 'None', 'bodyweight', 'Medium'),
  (91, 'Flutter Kicks', 'Lying on the back and performing small alternating leg kicks', 'None', 'bodyweight', 'High'),
  (92, 'Reverse Crunches', 'Lying on the back and bringing knees towards chest', 'None', 'bodyweight', 'Medium');
  (93, 'Parallel Bar Dips', 'Dips performed using parallel bars', 'Parallel bars', 'bodyweight', 'Medium'),
  (94, 'Bench Dips', 'Dips performed using a bench or step', 'Bench or step', 'bodyweight', 'Low'),
  (95, 'Chair Dips', 'Dips performed using a chair', 'Chair', 'bodyweight', 'Low'),
  (96, 'Ring Dips', 'Dips performed using gymnastic rings', 'Gymnastic rings', 'bodyweight', 'High'),
  (97, 'Assisted Tricep Dips', 'Dips performed with assistance from resistance bands or a partner', 'Resistance bands or partner', 'bodyweight', 'Medium'),
  (98, 'Weighted Tricep Dips', 'Dips performed with added weight', 'Weighted vest or dumbbell', 'bodyweight', 'High'),
  (99, 'Single Leg Tricep Dips', 'Dips performed with one leg lifted', 'Parallel bars or bench', 'bodyweight', 'Medium'),
  (100, 'Incline Tricep Dips', 'Dips performed with hands on an inclined surface', 'Incline bench or step', 'bodyweight', 'Low'),
  (101, 'Superman Hold', 'Hold the superman position for a specified duration', 'None', 'bodyweight', 'Low'),
  (102, 'Superman Raises', 'Perform raises of the arms and legs while in the superman position', 'None', 'bodyweight', 'Medium'),
  (103, 'Weighted Superman', 'Perform the superman exercise with added weight', 'Weighted vest or dumbbell', 'bodyweight', 'High'),
  (104, 'Single Arm Superman', 'Perform the superman exercise with one arm at a time', 'None', 'bodyweight', 'Medium'),
  (105, 'Superman Swimmers', 'Alternate raising and lowering opposite arm and leg while in the superman position', 'None', 'bodyweight', 'Medium'),
  (106, 'Superman Pulses', 'Perform small pulsing movements while holding the superman position', 'None', 'bodyweight', 'Medium'),
  (107, 'Superman Claps', 'Clap the hands together in front of the body while in the superman position', 'None', 'bodyweight', 'High'),
  (108, 'Superman Back Extensions', 'Perform back extensions while in the superman position', 'None', 'bodyweight', 'Medium')
  (109, 'Lizard Pose', 'Stretching the hip flexors and hamstrings', 'None', 'stretch', 'Low'),
  (110, 'Seated Forward Bend', 'Stretching the hamstrings and lower back while seated', 'None', 'stretch', 'Low'),
  (111, 'Bridge Pose', 'Stretching the back, chest, and hip flexors', 'None', 'stretch', 'Low'),
  (112, 'Seated Twist', 'Stretching the back and torso while seated', 'None', 'stretch', 'Low'),
  (113, 'Play Pose', 'Stretching the lower back and hips while in a kneeling position', 'None', 'stretch', 'Low'),
  (114, 'Standing Side Stretch', 'Stretching the sides of the body', 'None', 'stretch', 'Low'),
  (115, 'Kneeling Hip Flexor Stretch', 'Stretching the hip flexors while in a kneeling position', 'None', 'stretch', 'Low'),
  (116, 'Standing Calf Stretch', 'Stretching the muscles in the calves while standing', 'None', 'stretch', 'Low'),
  (117, 'Thread the Needle', 'Stretching the shoulders and upper back', 'None', 'stretch', 'Low'),
  (118, 'Downward Dog', 'Stretching the entire body with emphasis on the hamstrings and shoulders', 'None', 'stretch', 'Low')
  (119, 'Dumbbell Curl', 'Perform bicep curls using dumbbells.', 'Dumbbells', 'strength', 'Medium'),
  (120, 'Hammer Curl', 'Perform hammer curls using dumbbells.', 'Dumbbells', 'strength', 'Low'),
  (121, 'Dumbbell Bench Press', 'Perform bench press using dumbbells.', 'Dumbbells', 'strength', 'High',),
  (122, 'Incline Dumbbell Press', 'Perform incline bench press using dumbbells.', 'Dumbbells', 'strength', 'High',),
  (123, 'Seated Dumbbell Shoulder Press', 'Seated position, using dumbbells to press overhead, targeting the shoulders', 'Dumbbells', 'Strength', 'Medium');
  (124, 'Standing Barbell Shoulder Press', 'Standing position, using a barbell to press overhead, targeting the shoulders', 'Barbell', 'Strength', 'High');
  (125, 'Arnold Press', 'Seated or standing position, using dumbbells with a rotational movement, targeting the shoulders', 'Dumbbells', 'Strength', 'Medium');
  (126, 'Single-Arm Dumbbell Shoulder Press', 'Standing or seated position, using a single dumbbell to press overhead, targeting one shoulder at a time', 'Dumbbell', 'Strength', 'Medium');
  (127, 'Barbell Back Squat', 'Standing position, barbell placed on the upper back, bending the knees and hips to lower the body', 'Barbell', 'Strength Training', 'High');
  (128, 'Goblet Squat', 'Standing position, holding a dumbbell or kettlebell close to the chest, bending the knees and hips to lower the body', 'Dumbbell or Kettlebell', 'Strength Training', 'Medium');
  (129, 'Front Squat', 'Standing position, barbell placed on the front of the shoulders, bending the knees and hips to lower the body', 'Barbell', 'Strength Training', 'High');
  (130, 'Split Squat', 'Standing position, one leg positioned forward, bending the knees to lower the body, focusing on one leg at a time', 'None', 'Strength Training', 'Medium');
  (131, 'Sumo Squat', 'Standing position, feet wider than hip-width apart and toes pointed outward, bending the knees and hips to lower the body', 'None', 'Strength Training', 'Medium');
